apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: myapp
spec:
  containers:
    - name: redis-container
      image: rediss
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
